workflows:
  android-release:
    name: SimpMusic Release Build
    max_build_duration: 60
    environment:
      android_signing:
        - Simp
    scripts:
      - name: Create keystore.properties
        script: |
          echo "storeFile=$CM_KEYSTORE_PATH" > androidApp/keystore.properties
          echo "storePassword=$CM_KEYSTORE_PASSWORD" >> androidApp/keystore.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> androidApp/keystore.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> androidApp/keystore.properties
      - name: Build Release APK
        script: |
          ./gradlew :androidApp:assembleRelease -x :androidApp:uploadSentryProguardMappingsRelease
    artifacts:
      - androidApp/build/outputs/apk/**/*.apk
