workflows:
  android-release:
    name: SimpMusic Release Build
    max_build_duration: 60
    environment:
      android_signing:
        - Simp
    scripts:
      - name: Build Release APK
        script: |
          ./gradlew :androidApp:assembleRelease -x :androidApp:uploadSentryProguardMappingsRelease
    artifacts:
      - androidApp/build/outputs/apk/**/*.apk
