#!/bin/sh

SELF=$(readlink -f "$0")
HERE=${SELF%/*}
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)

cd $HERE

echo "Running SimpMusic..."
exec "${EXEC}" "$@"